# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-05 20:17
from __future__ import unicode_literals

from datetime import datetime
from django.db import migrations

import csv


def format_date(raw_string):
    if raw_string:
        return datetime.strptime(raw_string, '%d/%m/%Y %H:%M:%S')
    return None


def create_vehicles(apps, schema_editor):
    Vehicle = apps.get_model("core", "Vehicle")
    with open('csv_fixtures/vehicles.csv', 'r' ) as f:
        reader = csv.DictReader(f)
        for line in reader:
            Vehicle.objects.create(
                name=line['Vehicle'],
                registration=line['Registration'],
                year_manufactured=format_date(line['Year']),
                cost=line['Cost'] or None,
                year_purchased=format_date(line['Year Purchased']),
                vendor=line['From'],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180805_2027'),
    ]

    operations = [
        migrations.RunPython(create_vehicles)
    ]
