# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-05 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180805_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuel',
            old_name='price_prl_litre',
            new_name='price_per_litre',
        ),
        migrations.AlterField(
            model_name='fuel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
