# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-05 20:17
from __future__ import unicode_literals

from datetime import datetime
from django.db import migrations

import csv


def format_date(raw_string):
    if raw_string:
        return datetime.strptime(raw_string, '%d/%m/%Y %H:%M:%S')
    return None


def create_service(apps, schema_editor):
    Vehicle = apps.get_model('core', 'Vehicle')
    Service = apps.get_model('core', 'Service')
    with open('csv_fixtures/service.csv', 'r' ) as f:
        reader = csv.DictReader(f)
        for line in reader:
            vehicle = Vehicle.objects.get(name=line['Vehicle'])
            Service.objects.create(
                vehicle=vehicle,
                type_of_service=line['Type Of Service'],
                materials=line['Materials'],
                oil=line['Oil'],
                diesel_filter=line['Diesel Filter'],
                air_filter=line['Air Filter'],
                miles=line['Miles'],
                date=format_date(line['Date']),
                cost=line['Cost'] or None,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180805_2046'),
    ]

    operations = [
        migrations.RunPython(create_service)
    ]
