# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-06 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180806_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='fuel',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='price_per_litre',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=b'Price per litre in pounds and pence.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
