# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180806_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='fuel',
            name='price_per_litre',
            field=models.DecimalField(blank=True, decimal_places=3, help_text=b'Price per litre in pounds and pence.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=24),
        ),
    ]
