# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-10-12 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181027_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='fuel',
            name='price_per_litre',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Price per litre in pounds and pence.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='electricmeterreading',
            name='documents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Document'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='documents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Document'),
        ),
        migrations.AddField(
            model_name='housecontents',
            name='documents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Document'),
        ),
        migrations.AddField(
            model_name='service',
            name='documents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Document'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='documents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Document'),
        ),
    ]
