# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-10-12 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0010_auto_20221012_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricmeterreading',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='housecontents',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='service',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='documents',
        ),
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
